spring:
  profiles:
    active: dev

logging:
  level:
    org:
      springframework:
        security: DEBUG

application:
  security:
    public-paths:
      - GET::/api/v1/users/**
      - GET::/api/v1/courses/**
      - POST::/authenticate/**
      - POST::/refresh/**
      - GET::/swagger-ui/**
      - GET::/v3/api-docs/**
    ignore-paths:
      - /api/v1/users
      - /v2/api-docs
      - /v3/api-docs
      - /swagger-ui/**
      - /swagger-resources/**
      - /*/swagger-resources/**
      - /*/v2/api-docs

jwt:
  secret: bHDrS4XCmC7eK7LzMhzH5Wadv62XveDM4GfbVjOn
  expire-length: 300
  refresh-expiration-date: 600
  one-token-mode: false
