spring:
  datasource:
    username: study_sp
    url: jdbc:postgresql://103.106.104.57:5432/study_sp
    password: ky5kesaMXcJmFLB5
  jpa:
    properties:
      hibernate:
        default_schema: app
    hibernate:
      ddl-auto: update
    show-sql: true
  data:
    redis:
      host: 103.106.104.57
      port: 8201
      password: my-password
  flyway:
    schemas: app
    defaultSchema: app
    locations: classpath:db/migration
#    baseline-version: 0
#    baseline-on-migrate: true

