spring:
  profiles:
    active: dev

logging:
  level:
    org:
      springframework:
        security: DEBUG

application:
  security:
    ignore-paths:
      - /pages/**
      - /js/***
      - /api/v1/auth/**
      - /v2/api-docs
      - /v3/api-docs
      - /swagger-ui/**
      - /swagger-resources/**
      - /*/swagger-resources/**
      - /*/v2/api-docs
      - /v3/api-docs/**

jwt:
  secret: bHDrS4XCmC7eK7LzMhzH5Wadv62XveDM4GfbVjOn
  expire-length: 300
  refresh-expiration-date: 600
  one-token-mode: false

server:
  timezone: Asia/Ho_Chi_Minh
  port: 8080
