business:
  exception:
    invalid_input: Invalid input.
    duplicate_entry: Duplicate entry found.
    insufficient_funds: Insufficient funds to perform transaction.
  exception_code:
    invalid_format: CODE_INVALID_FORMAT
    not_found: CODE_NOT_FOUND
    unprocessable_entity: CODE_UNPROCESSABLE_ENTITY
  success:
    operation_completed: Operation completed successfully.
  security:
    authentication_failed: Authentication failed.
    unauthorized_access: Unauthorized access.

